dev:
  restart: always
  build: .
  ports:
    - "3000:3000"
    - "3001:3001"
    - "5000:5000"
    - "8080:8080"
    - "8888:8888"
    - "2222:22"
  links:
    - mongo
  volumes:
    - ./data/work:/home/devenv/work

mongo:
  restart: always
  image: mongo
  volumes:
    - ./data/mongodb/db:/data/db
